version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: collabdesk-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collabdesk
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-main:
    image: redis:7
    container_name: collabdesk-main-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_main_data:/data
      - ./redis/redis-main.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  redis-network:
    driver: bridge

volumes:
  postgres_data:
  redis_main_data:
